server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=order_management;encrypt=false;trustServerCertificate=true
    username: soliz
    password: springboot_egitron
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

  #security:
   # user:
      #name: admin
      #password: admin123
