server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=order_management;encrypt=false;trustServerCertificate=true;
    username: soliz
    password: springboot_egitron
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 49fad66c5d45e1
    password: 85e3ca7e2d0205
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  app:
    report:
      mail-to: fredericosoliz@gmail.com


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

logging:
  level:
    org.springframework.security: TRACE


      #security:
   # user:
      #name: admin
      #password: admin123
